### ISSUE TITLE
still having issue with timestamp

### ISSUE THREAD

**Issue by greatestukonu** [sazanrjb/OfficeManagementSystem#2]

**Comment by greatestukonu** [comment]
and i am finding it difficult to update my laravel and php

**Comment by greatestukonu** [comment]
still having issue with timestamp

**Comment by sajxraj** [comment]
Please write your problem clearly

**Comment by greatestukonu** [comment]
When I want to create user I get timestamp error

**Comment by sajxraj** [comment]
Create a user from the system? Does it mean you are able to log in?

**Comment by greatestukonu** [comment]
Yes

**Comment by sajxraj** [comment]
Ok please provide the traced error

**Comment by greatestukonu** [comment]
Or is it because of the versions of Iaravel I'm using

**Comment by greatestukonu** [comment]
Laravel 3.1

**Comment by greatestukonu** [comment]
I tried downloading current version but it wasn't working

**Comment by sajxraj** [comment]
Now I am even more confused. Mail me at sazanrjb@gmail.com if you want any assistance. Thanks.
