### ISSUE TITLE
in the project

### ISSUE THREAD

**Issue by greatestukonu** [sazanrjb/OfficeManagementSystem#4]
bacause i can only see the username and not password

**Comment by sajxraj** [comment]
the username created is the password itself. Please go through the code as well. @greatestukonu

**Comment by greatestukonu** [comment]
Because it's not generating...i have check

**Comment by sajxraj** [comment]
so what is stored in the password field in `users` table, while creating a user?

**Comment by greatestukonu** [comment]
Nothing

**Comment by sajxraj** [comment]
can you post a screenshot of the `users` table here?

**Comment by greatestukonu** [comment]
Ok

**Comment by greatestukonu** [comment]
that is a screenshot of table user

**Comment by greatestukonu** [comment]
Good evening  Please you have not repiled. I sent the screenshot to you
this morning

**Comment by sajxraj** [comment]
where is the screenshot?

**Comment by greatestukonu** [comment]
i have sent the screenshoot
